spring:
  datasource:
    mytest:
      username: root
      password: '123456'
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3306/mytest?serverTimezone=Asia/Shanghai